"""
Entity mappings for mall stores, dining, services, and entertainment
"""

import logging
from typing import Optional

# Get logger - will use the one configured in main.py
workflow_logger = logging.getLogger("workflow")

store_mapping = {
    "gadgets": "store",
    "taana baana": "store",
    "sam's abaya": "store",
    "eastern art & handicrafts": "store",
    "ximi vogue": "store",
    "jacob jones": "store",
    "branded wear": "store",
    "saylani welfare trust": "store",
    "zamin jewellers": "store",
    "tar kashi": "store",
    "traditional khusa": "store",
    "just fragrance": "store",
    "bonanza satrangi": "store",
    "aroma concepts": "store",
    "alpha accessories": "store",
    "glamour bag": "store",
    "mehran jeweller": "store",
    "tajik traditional": "store",
    "al raj currency exchange": "store",
    "time zone": "store",
    "thai zone": "store",
    "almond & co": "store",
    "friends corporation": "store",
    "d watson": "store",
    "saeed ghani": "store",
    "johri": "store",
    "readers point": "store",
    "ndure": "store",
    "brand city": "store",
    "bata": "store",
    "majhoorat": "store",
    "little explorer": "store",
    "millie shoes": "store",
    "seveston": "store",
    "the linen company": "store",
    "crown diamond": "store",
    "kohinoor": "store",
    "zambeel": "store",
    "style & comfort": "store",
    "mobile gadgets": "store",
    "mr kazi": "store",
    "brand ministry": "store",
    "younique": "store",
    "zero": "store",
    "bloon": "store",
    "haroons": "store",
    "location": "store",
    "babydayout": "store",
    "service": "store",
    "khaadi": "store",
    "limelight": "store",
    "lady privacy": "store",
    "adoro": "store",
    "mocciani": "store",
    "cougar": "store",
    "style in shoe": "store",
    "khussa factory": "store",
    "batik studio": "store",
    "skechers": "store",
    "dockers": "store",
    "levis": "store",
    "maria b": "store",
    "mtj": "store",
    "ghenie": "store",
    "sonachandi": "store",
    "dari mooch": "store",
    "samsung": "store",
    "j fragrance": "store",
    "hussain jewller": "store",
    "adidas": "store",
    "jaferjees": "store",
    "lulusar": "store",
    "royal tag": "store",
    "1st step": "store",
    "ultra club": "store",
    "tayyab jewller": "store",
    "apavi shoe": "store",
    "apavi": "store",
    "coppelia": "store",
    "miniso": "store",
    "breakout": "store",
    "charcoal": "store",
    "monark": "store",
    "focus": "store",
    "swarovski": "store",
    "tagheuer": "store",
    "bodyshop": "store",
    "gulzari optics": "store",
    "rewaj jewllers": "store",
    "al syed optics": "store",
    "hunza emporium": "store",
    "hub": "store",
    "julke": "store",
    "kef diamonds": "store",
    "jc buckman": "store",
    "maybelline": "store",
    "engine": "store",
    "equator": "store",
    "speed sports": "store",
    "crocs": "store",
    "miracle": "store",
    "almirah": "store",
    "cross stitch": "store",
    "saya": "store",
    "sapphire": "store",
    "fpl": "store",
    "ethnic": "store",
    "naqshi": "store",
    "hush puppies": "store",
    "tesoro": "store",
    "hop scotch": "store",
    "insignia": "store",
    "anta": "store",
    "hemani": "store",
    "scents and secrets": "store",
    "rios": "store",
    "beechtree": "store",
    "uniworth black": "store",
    "diners": "store",
    "ecs": "store",
    "almas": "store",
    "one": "store",
    "unze london": "store",
    "zubaida": "store",
    "edenrobe": "store",
    "lawrencepur": "store",
    "stylo": "store",
    "toyclub": "store",
    "generation": "store",
    "zeen": "store",
    "the souvenir shop": "store",
    "siraj 7 sons": "store",
    "elegant makeup city": "store",
    "dynasty": "store",
    "batik": "store",
    "nakoosh": "store",
    "cambridge": "store",
    "alkaram & lifestyle": "store",
    "junaid jamshed": "store",
    "variety cosmetics & bags": "store",
    "ideas by gul ahmed": "store",
    "nishat": "store",
    "outfitter": "store",
    "borjan": "store",
    "corio": "store",
    "keyseria": "store",
    "tiny ears": "store",
    "little people": "store",
    "bonanza": "store",
    "m basic": "store",
    "mona": "store",
    "threads & motifs": "store",
    "logo shoes": "store",
    "oaks": "store",
    "sohaye": "store",
    "amir adnan": "store",
    "furor": "store",
    "sana safinaz": "store",
    "satrangi": "store",
    "charizma": "store",
    "breeze": "store",
    "minnie minor": "store",
    "chinyere": "store",
    "abc fragrance": "store",
    "hi volts": "store",
    "revolution": "store",
    "sowears": "store",
    "chunri by jalips": "store",
    "rth": "store",
    "brackets": "store",
    "excel": "store",
    "amd": "store",
    "coco republic": "store",
    "ali baba": "store",
    "dollar store": "store",
    "pound store": "store",
    "toyland": "store",
    "361 degree": "store",
    "dollar world": "store",
    "doll house": "store",
    "mirhal": "store",
    "zebaish": "store",
    "multani art": "store",
    "khusa store": "store",
    "time n space": "store",
    "designer vault": "store",
    "tiny tots": "store",
    "just for men": "store",
    "yageen": "store",
    "khusas store": "store",
    "mip.j": "store",
    "north face": "store",
    "sohaib's art": "store",
    "jockey": "store",
    "kumas": "store",
    "kundan": "store",
    "originals of london": "store",
    "good lif": "store",
    "anamta fateh": "store",
    "a&i mob accessorries": "store",
    "anya jewlery": "store",
    "dare to dazel": "store",
    "irhas kids": "store",
    "sns fragrances": "store",
    "joy station": "store",
    "leisure club": "store",
    "rollover": "store",
    "minime": "store"
}
dine_mapping = {
    "wildwings": "dine",
    "pizza hut": "dine",
    "tayto": "dine",
    "kababjees": "dine",
    "pepe's piri piri": "dine",
    "hardees": "dine",
    "mcDonalds": "dine",
    "spice factory": "dine",
    "juices island": "dine",
    "rewayat": "dine",
    "yumto": "dine",
    "malangi": "dine",
    "kfc": "dine",
    "pizza n pasta": "dine",
    "chachajee": "dine",
    "sufi x press": "dine",
    "darkside": "dine",
    "pita & happy": "dine",
    "optp": "dine",
    "al baik": "dine",
    "tawa chatkhara": "dine",
    "red apple": "dine",
    "howdy": "dine",
    "ice curl": "dine",
    "bubluda": "dine",
    "cheezious": "dine",
    "jojo foods": "dine",
    "cigerates & choclates": "dine",
    "food mood": "dine",
    "true taste": "dine",
    "eklairs": "dine",
    "gloria jeans": "dine",
    "islamic honey": "dine",
    "the potato factory": "dine",
    "coffee planet": "dine",
    "frutastic": "dine",
    "timhortons": "dine",
    "baskin robbins": "dine",
    "juice station": "dine",
    "pop nosh": "dine",
    "kingcorn": "dine",
    "juice fruity": "dine",
    "ghosez": "dine",
    "cinnabon": "dine",
    "jelly factory": "dine",
    "balochistan dry fruit": "dine"
}
service_mapping = {
    "pakistan currency exchange": "service",
    "ubl bank": "service",
    "dubai islamic bank": "service",
    "carefour": "service"
}
entertainment_mapping = {
    "fun city": "entertainment",
    "space craft": "entertainment",
    "cinepax": "entertainment"
}


def get_entity_category(entity_name: str) -> Optional[str]:
    """
    Get category for an entity name by checking all mappings
    
    Args:
        entity_name: Normalized entity name (lowercase, no punctuation)
        
    Returns:
        Category string: "store", "dine", "service", "entertainment", or None if not found
    """
    entity_lower = entity_name.lower().strip()
    workflow_logger.info(f"    → Looking up entity '{entity_lower}' in mappings...")
    
    # Check all mappings
    if entity_lower in store_mapping:
        category = store_mapping[entity_lower]
        workflow_logger.info(f"    → Found in store_mapping → Category: '{category}'")
        return category
    elif entity_lower in dine_mapping:
        category = dine_mapping[entity_lower]
        workflow_logger.info(f"    → Found in dine_mapping → Category: '{category}'")
        return category
    elif entity_lower in service_mapping:
        category = service_mapping[entity_lower]
        workflow_logger.info(f"    → Found in service_mapping → Category: '{category}'")
        return category
    elif entity_lower in entertainment_mapping:
        category = entertainment_mapping[entity_lower]
        workflow_logger.info(f"    → Found in entertainment_mapping → Category: '{category}'")
        return category
    
    workflow_logger.warning(f"    → Entity '{entity_lower}' NOT FOUND in any mapping")
    return None


# Combined mapping for easy lookup
entity_mapping = {**store_mapping, **dine_mapping, **service_mapping, **entertainment_mapping}
